=== hallatech/automated-deployment-system/platforms/atg/config/application/applications.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--W3C Schema generated by XMLSpy v2010 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="ST_source">
		<xs:restriction base="xs:string">
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ST_destination">
		<xs:restriction base="xs:string">
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Slot_restriction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PS"/>
			<xs:enumeration value="LMPrimary"/>
			<xs:enumeration value="LMSecondary"/>
			<xs:enumeration value="CtrlPrimary"/>
			<xs:enumeration value="CtrlSecondary"/>
		</xs:restriction>
	</xs:simpleType>	
	<xs:element name="slotItem">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_slotItem">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="file"/>
								<xs:enumeration value="folder"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="serverItem">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_slotItem">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="file"/>
								<xs:enumeration value="folder"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>	
	<xs:element name="AtgDataItem">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_AtgDataItem">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="file"/>
								<xs:enumeration value="folder"/>
              				</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="slotType" use="required">
						<xs:simpleType>
							<xs:restriction base="Slot_restriction">
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="source">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_source">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="file"/>
								<xs:enumeration value="folder"/>
								<xs:enumeration value="explodedEar"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="slot">
		<xs:complexType>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="Slot_restriction"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="order" use="required">
				<xs:simpleType>
					<xs:restriction base="ST_number"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="otherSlots">
		<xs:complexType>
			<xs:attribute name="order" use="required">
				<xs:simpleType>
					<xs:restriction base="ST_number"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="slotTypeStartupOrder">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="slot" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="default" use="required">
				<xs:simpleType>
					<xs:restriction base="ST_number">
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="restartStrategy">
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="OneAtATimeRestartStrategy"/>
						<xs:enumeration value="ServerRoundRobinRestartStrategy"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="startStop">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="restartStrategy" maxOccurs="1" minOccurs="0"/>
				<xs:element ref="slotTypeStartupOrder" maxOccurs="1" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="deleteFromAtgData">
		<xs:complexType>      
			<xs:sequence>
				<xs:element ref="AtgDataItem" maxOccurs="unbounded" minOccurs="1"/>
			</xs:sequence>    
		</xs:complexType>
	</xs:element>
	<xs:element name="deleteFromSlot">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="slotItem" maxOccurs="unbounded" minOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="slotType" use="optional">
				<xs:simpleType>
					<xs:restriction base="Slot_restriction">
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="deleteFromServer">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="serverItem" maxOccurs="unbounded" minOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="item">
		<xs:complexType>  
			<xs:sequence>
				<xs:element ref="source"/>
				<xs:element ref="destination"/>
			</xs:sequence>
      		<xs:attribute name="extractAtTarget" use="optional" default="false">
        		<xs:simpleType>
          			<xs:restriction base="xs:boolean">
          			</xs:restriction>
        		</xs:simpleType>        
      		</xs:attribute>
			<xs:attribute name="slotType" use="optional">
				<xs:simpleType>
					<xs:restriction base="Slot_restriction">
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="destination">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_destination">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="file"/>
								<xs:enumeration value="folder"/>
                				<xs:enumeration value="tempArchive"/>
              				</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
          			<xs:attribute name="receiver" use="required">
            			<xs:simpleType>
              				<xs:restriction base="xs:string">
                				<xs:enumeration value="slot"/>
                				<xs:enumeration value="server"/>
              				</xs:restriction>
            			</xs:simpleType>
          			</xs:attribute>
        		</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="buildinput">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="item" maxOccurs="unbounded" minOccurs="0"/>
				<xs:element ref="deleteFromSlot" maxOccurs="unbounded" minOccurs="0"/>
				<xs:element ref="deleteFromServer" maxOccurs="unbounded" minOccurs="0"/>				
				<xs:element ref="deleteFromAtgData" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="applications">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="application" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="application">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="startStop" maxOccurs="1" minOccurs="0"/>
				<xs:element ref="buildinput"/>
			</xs:sequence>
			<xs:attribute name="type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="BACK"/>
						<xs:enumeration value="FRONT"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" use="required">
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="ST_slotItem">
		<xs:restriction base="xs:string"></xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="ST_AtgDataItem">
		<xs:restriction base="xs:string"></xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="ST_number">
		<xs:restriction base="xs:int"></xs:restriction>
	</xs:simpleType>
</xs:schema>

=== hallatech/automated-deployment-system/platforms/atg/config/application/applications.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<applications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="applications.xsd">
	<application name="All">
		<startStop>
			<!-- restartStrategy name="OneAtATimeRestartStrategy"/-->
			<restartStrategy name="ServerRoundRobinRestartStrategy"/>
			<slotTypeStartupOrder default="10">
				<slot type="LMPrimary" order="1"/>
				<slot type="LMSecondary" order="2"/>
				<slot type="CtrlPrimary" order="3"/>
				<slot type="CtrlSecondary" order="4"/>
				<slot type="PS" order="5"/>
			</slotTypeStartupOrder>
		</startStop>
		
		<buildinput>
			<deleteFromSlot>
				<slotItem type="folder">deploy/ROOT.war</slotItem>
			</deleteFromSlot>

			<!-- JBoss slimming -->
			<deleteFromSlot>
				<!-- Remove Hypersonic database -->
				<slotItem type="file">deploy/hsqldb-ds.xml</slotItem>
				<slotItem type="file">deploy/messaging/hsqldb-persistence-service.xml</slotItem>
				<!-- Remove EJB3 services -->
				<slotItem type="file">deploy/ejb3-connectors-jboss-beans.xml</slotItem>
				<slotItem type="file">deploy/ejb3-container-jboss-beans.xml</slotItem>
				<slotItem type="file">deploy/ejb3-interceptors-aop.xml</slotItem>
				<slotItem type="file">deploy/ejb3-timerservice-jboss-beans.xml</slotItem>
				<slotItem type="file">deployers/jboss-ejb3-endpoint-deployer.jar</slotItem>
				<slotItem type="file">deployers/ejb3-deployers-jboss-beans.xml</slotItem>
				<!-- Remove EJB2 services -->
				<slotItem type="file">deploy/ejb2-container-jboss-beans.xml</slotItem>
				<!-- slotItem type="file">deploy/ejb2-timer-service.xml</slotItem-->
				<!-- Remove UUID Key Generator -->
				<slotItem type="folder">deploy/uuid-key-generator.sar</slotItem>
				<!-- Remove JUDDI -->
				<slotItem type="folder">deploy/juddi-service.sar</slotItem>
				<!-- Remove JBoss Mail -->
				<slotItem type="file">deploy/mail-service.xml</slotItem>
				<slotItem type="folder">deploy/mail-ra.rar</slotItem>
				<!-- Remove JBoss Scheduling -->
				<slotItem type="file">deploy/schedule-manager-service.xml</slotItem>
				<slotItem type="file">deploy/scheduler-service.xml</slotItem>
				<!-- Remove Bsh Deployer-->
				<slotItem type="folder">deployers/bsh.deployer</slotItem>
				<!-- Remove JBossWS -->
				<slotItem type="file">conf/jax-ws-catalog.xml</slotItem>
				<slotItem type="file">conf/props/jbossws-roles.properties</slotItem>
				<slotItem type="file">conf/props/jbossws-users.properties</slotItem>
				<slotItem type="folder">deploy/jbossws.sar</slotItem>
				<slotItem type="folder">deployers/jbossws.deployer</slotItem>
				<!-- Remove Seam -->
				<slotItem type="folder">deploy/admin-console.war</slotItem>
				<slotItem type="folder">deployers/seam.deployer</slotItem>
				<!-- Remove IIOP/Corba -->
				<slotItem type="file">conf/jacorb.properties</slotItem>
				<slotItem type="file">deploy/iiop-service.xml</slotItem>
				<slotItem type="file">deployers/ejb3.deployer/META-INF/ejb3-iiop-deployers-jboss-beans.xml</slotItem>
				<slotItem type="file">lib/jacorb.jar</slotItem>
			</deleteFromSlot>
			
			<deleteFromServer>
				<!-- Update CGLib -->
				<serverItem type="file">common/lib/cglib.jar</serverItem>
			</deleteFromServer>
			
		</buildinput>
	</application>
	<application name="LiveStoreFront" type="FRONT">
		<buildinput>
			<item slotType="PS">
				<source type="file">deploy/LiveStoreFront.ear</source>
				<destination type="folder" receiver="slot">deploy</destination>
			</item>
			<item slotType="CtrlPrimary">
				<source type="file">deploy/LiveStoreFront.ear</source>
				<destination type="folder" receiver="slot">deploy</destination>
			</item>
			<item slotType="CtrlSecondary">
				<source type="file">deploy/LiveStoreFront.ear</source>
				<destination type="folder" receiver="slot">deploy</destination>
			</item>
			<item slotType="LMPrimary">
				<source type="file">deploy/Minimal.ear</source>
				<destination type="folder" receiver="slot">deploy</destination>
			</item>
			<item slotType="LMSecondary">
				<source type="file">deploy/Minimal.ear</source>
				<destination type="folder" receiver="slot">deploy</destination>
			</item>
		</buildinput>
	</application>
	<application name="StagingStoreFront" type="BACK">
		<buildinput>
			<item slotType="PS">
				<source type="file">deploy/StagingStoreFront.ear</source>
				<destination type="folder" receiver="slot">deploy</destination>
			</item>
			<item slotType="CtrlPrimary">
				<source type="file">deploy/StagingStoreFront.ear</source>
				<destination type="folder" receiver="slot">deploy</destination>
			</item>
			<item slotType="CtrlSecondary">
				<source type="file">deploy/StagingStoreFront.ear</source>
				<destination type="folder" receiver="slot">deploy</destination>
			</item>
			<item slotType="LMPrimary">
				<source type="file">deploy/Minimal.ear</source>
				<destination type="folder" receiver="slot">deploy</destination>
			</item>
			<item slotType="LMSecondary">
				<source type="file">deploy/Minimal.ear</source>
				<destination type="folder" receiver="slot">deploy</destination>
			</item>
		</buildinput>
	</application>
	<application name="ContentAdmin" type="BACK">
		<buildinput>
			<item slotType="PS">
				<source type="file">deploy/ContentAdmin.ear</source>
				<destination type="folder" receiver="slot">deploy</destination>
			</item>
			<item slotType="CtrlPrimary">
				<source type="file">deploy/ContentAdmin.ear</source>
				<destination type="folder" receiver="slot">deploy</destination>
			</item>
			<item slotType="CtrlSecondary">
				<source type="file">deploy/ContentAdmin.ear</source>
				<destination type="folder" receiver="slot">deploy</destination>
			</item>
			<item slotType="LMPrimary">
				<source type="file">deploy/Minimal.ear</source>
				<destination type="folder" receiver="slot">deploy</destination>
			</item>
			<item slotType="LMSecondary">
				<source type="file">deploy/Minimal.ear</source>
				<destination type="folder" receiver="slot">deploy</destination>
			</item>
		</buildinput>
	</application>
</applications>
