=== hallatech/automated-deployment-system/platforms/atg/config/environment/environment.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="spindrift">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="environment" maxOccurs="unbounded">	
					<xs:complexType>
						<xs:sequence>
							<xs:element name="servergroup" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="server" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
												  <xs:element name="slot" maxOccurs="unbounded">
												    <xs:complexType>
												    	<xs:sequence>
												    		<xs:element name="jvm_opts" type="xs:string"/>
												    	</xs:sequence>
														<xs:attribute name="name" use="required">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="slot[1-6]"/>
  															</xs:restriction>
														 </xs:simpleType>
														</xs:attribute>
														<xs:attribute name="type" use="required">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="LMPrimary"/>
																<xs:enumeration value="LMSecondary"/>
																<xs:enumeration value="LM2Primary"/>
																<xs:enumeration value="LM2Secondary"/>
																<xs:enumeration value="CtrlPrimary"/>
																<xs:enumeration value="CtrlSecondary"/>
																<xs:enumeration value="PS"/>
  															</xs:restriction>
														 </xs:simpleType>
														 </xs:attribute>
														<xs:attribute name="clustered" type="xs:boolean" use="optional"/>
												     	<xs:attribute name="jbossDomain" type="xs:string" use="optional"/>
														<xs:attribute name="jbossClusterMCastAddr" type="xs:string" use="required"/>
													    <xs:attribute name="logFileRetentionDays" type="xs:integer" use="required"/>
														<xs:attribute name="loadBearing" type="xs:boolean" use="optional" default="true"/>
												    </xs:complexType>
												  </xs:element>
												</xs:sequence>
												<xs:attribute name="name" type="xs:string" use="required"/>
												<xs:attribute name="LM" type="xs:boolean" use="optional" default="false"/>
											</xs:complexType>
											<xs:unique name="SlotName">
												<xs:selector xpath="slot"/>
												<xs:field xpath="@name"/>
    										</xs:unique>
										</xs:element>
									</xs:sequence>								
									<xs:attribute name="application" type="xs:string" use="required"/>
									<xs:attribute name="jbossCluster" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
    				<xs:unique name="ServerName">
      					<xs:selector xpath="servergroup/server"/>
      					<xs:field xpath="@name"/>
    				</xs:unique>					
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== hallatech/automated-deployment-system/platforms/atg/config/environment/environment.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<spindrift xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="environment.xsd">

<environment name="LOCAL">
	<servergroup application="LiveStoreFront" jbossCluster="ATG_LIVE_LOCAL">
		<server name="locallive1">
			<slot name="slot1" type="LMPrimary" jbossDomain="LM1" logFileRetentionDays="20" jbossClusterMCastAddr="239.255.1.10">
				<jvm_opts>-server -Xms384M -Xmx768M -XX:PermSize=128m -XX:MaxPermSize=128m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:\\\${JBOSS_HOME}/server/SLOT_NAME/log/gc.log -Djboss.platform.mbeanserver</jvm_opts>
			</slot>
			<slot name="slot2" type="PS" jbossDomain="A1" logFileRetentionDays="20" jbossClusterMCastAddr="239.255.1.11">
				<jvm_opts>-server -Xms1024M -Xmx1024M -XX:PermSize=128m -XX:MaxPermSize=256m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:\\\${JBOSS_HOME}/server/SLOT_NAME/log/gc.log -Djboss.platform.mbeanserver</jvm_opts>
			</slot>
		</server>
	</servergroup>
	<servergroup application="ContentAdmin" jbossCluster="ATG_CA_LOCAL">
		<server name="localca1">
			<slot name="slot1" type="LMPrimary" jbossDomain="LM1" logFileRetentionDays="20" jbossClusterMCastAddr="239.255.1.12">
				<jvm_opts>-server -Xms1024M -Xmx1024M -XX:PermSize=128m -XX:MaxPermSize=256m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:\\\${JBOSS_HOME}/server/SLOT_NAME/log/gc.log -Djboss.platform.mbeanserver</jvm_opts>
			</slot>
			<slot name="slot2" type="PS" jbossDomain="A1" logFileRetentionDays="20" jbossClusterMCastAddr="239.255.1.13">
				<jvm_opts>-server -Xms1024M -Xmx1024M -XX:PermSize=128m -XX:MaxPermSize=256m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:\\\${JBOSS_HOME}/server/SLOT_NAME/log/gc.log -Djboss.platform.mbeanserver</jvm_opts>
			</slot>
		</server>
	</servergroup>
</environment>


<environment name="AVE">
	<servergroup application="LiveStoreFront" jbossCluster="ATG_LIVE_AVE">
		<server name="ssf-ave-4">
			<slot name="slot1" type="LMPrimary" jbossDomain="LM1" jbossClusterMCastAddr="239.255.2.10" logFileRetentionDays="20">
				<jvm_opts>-server -Xms1024M -Xmx1024M -XX:PermSize=128m -XX:MaxPermSize=256m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:\\\${JBOSS_HOME}/server/SLOT_NAME/log/gc.log -Datg.dynamo.layers=ave -Djboss.platform.mbeanserver</jvm_opts>
			</slot>
			<slot name="slot2" type="CtrlPrimary" jbossDomain="CTRL1" jbossClusterMCastAddr="239.255.2.11" logFileRetentionDays="20">
				<jvm_opts>-server -Xms1024M -Xmx1024M -XX:PermSize=128m -XX:MaxPermSize=256m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:\\\${JBOSS_HOME}/server/SLOT_NAME/log/gc.log -Datg.dynamo.layers=ave -Djboss.platform.mbeanserver</jvm_opts>
			</slot>
			<slot name="slot3" type="PS" jbossDomain="A1" jbossClusterMCastAddr="239.255.2.12" logFileRetentionDays="5">
				<jvm_opts>-server -Xms1024M -Xmx1024M -XX:PermSize=128m -XX:MaxPermSize=256m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:\\\${JBOSS_HOME}/server/SLOT_NAME/log/gc.log -Datg.dynamo.layers=ave -Djboss.platform.mbeanserver</jvm_opts>
			</slot>
			<slot name="slot4" type="PS" jbossDomain="A1" jbossClusterMCastAddr="239.255.2.12" logFileRetentionDays="5">
				<jvm_opts>-server -Xms1024M -Xmx1024M -XX:PermSize=128m -XX:MaxPermSize=256m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:\\\${JBOSS_HOME}/server/SLOT_NAME/log/gc.log -Datg.dynamo.layers=ave -Djboss.platform.mbeanserver</jvm_opts>
			</slot>
		</server>
	</servergroup>
	
	<servergroup application="StagingStoreFront" jbossCluster="ATG_STAGE_AVE">
		<server name="ssf-ave-9">
			<slot name="slot1" type="LMPrimary" jbossDomain="LM1" jbossClusterMCastAddr="239.255.2.13" logFileRetentionDays="20">
				<jvm_opts>-server -Xms1024M -Xmx1024M -XX:PermSize=128m -XX:MaxPermSize=256m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:\\\${JBOSS_HOME}/server/SLOT_NAME/log/gc.log -Datg.dynamo.layers=ave -Djboss.platform.mbeanserver</jvm_opts>
			</slot>
			<slot name="slot2" type="CtrlPrimary" jbossDomain="CTRL1" jbossClusterMCastAddr="239.255.2.14" logFileRetentionDays="20">
				<jvm_opts>-server -Xms1024M -Xmx1024M -XX:PermSize=128m -XX:MaxPermSize=256m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:\\\${JBOSS_HOME}/server/SLOT_NAME/log/gc.log -Datg.dynamo.layers=ave -Djboss.platform.mbeanserver</jvm_opts>
			</slot>
			<slot name="slot3" type="PS" jbossDomain="A1" jbossClusterMCastAddr="239.255.2.15" logFileRetentionDays="5">
				<jvm_opts>-server -Xms1024M -Xmx1024M -XX:PermSize=128m -XX:MaxPermSize=256m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:\\\${JBOSS_HOME}/server/SLOT_NAME/log/gc.log -Datg.dynamo.layers=ave -Djboss.platform.mbeanserver</jvm_opts>
			</slot>
			<slot name="slot4" type="PS" jbossDomain="A1" jbossClusterMCastAddr="239.255.2.15" logFileRetentionDays="5">
				<jvm_opts>-server -Xms1024M -Xmx1024M -XX:PermSize=128m -XX:MaxPermSize=256m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:\\\${JBOSS_HOME}/server/SLOT_NAME/log/gc.log -Datg.dynamo.layers=ave -Djboss.platform.mbeanserver</jvm_opts>
			</slot>
		</server>
	</servergroup>
</environment>


<environment name="CI">
	<servergroup application="LiveStoreFront" jbossCluster="ATG_LIVE_CI">
		<server name="NLATGDPAG01">
			<slot name="slot1" type="LMPrimary" jbossDomain="LM1" logFileRetentionDays="20" jbossClusterMCastAddr="239.255.3.10">
				<jvm_opts>-server -Xms1536M -Xmx1536M -XX:PermSize=256m -XX:MaxPermSize=512m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:\\\${JBOSS_HOME}/server/SLOT_NAME/log/gc.log -Datg.dynamo.layers=ci -Djboss.platform.mbeanserver</jvm_opts>
			</slot>
			<slot name="slot2" type="CtrlPrimary" jbossDomain="CTRL1" logFileRetentionDays="20" jbossClusterMCastAddr="239.255.3.11">
				<jvm_opts>-server -Xms1536M -Xmx1536M -XX:PermSize=256m -XX:MaxPermSize=512m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:\\\${JBOSS_HOME}/server/SLOT_NAME/log/gc.log -Datg.dynamo.layers=ci -Djboss.platform.mbeanserver</jvm_opts>
			</slot>
			<slot name="slot3" type="PS" jbossDomain="A1" logFileRetentionDays="5" jbossClusterMCastAddr="239.255.3.12">
				<jvm_opts>-server -Xms1536M -Xmx1536M -XX:PermSize=256m -XX:MaxPermSize=512m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:\\\${JBOSS_HOME}/server/SLOT_NAME/log/gc.log -Datg.dynamo.layers=ci -Djboss.platform.mbeanserver</jvm_opts>
			</slot>
			<slot name="slot4" type="PS" jbossDomain="A1" logFileRetentionDays="5" jbossClusterMCastAddr="239.255.3.12">
				<jvm_opts>-server -Xms1536M -Xmx1536M -XX:PermSize=256m -XX:MaxPermSize=512m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:\\\${JBOSS_HOME}/server/SLOT_NAME/log/gc.log -Datg.dynamo.layers=ci -Djboss.platform.mbeanserver</jvm_opts>
			</slot>
		</server>
	</servergroup>
	
	<servergroup application="StagingStoreFront" jbossCluster="ATG_STAGE_CI">
		<server name="NLATGDSTG01">
			<slot name="slot1" type="LMPrimary" jbossDomain="LM1" logFileRetentionDays="20" jbossClusterMCastAddr="239.255.3.13">
				<jvm_opts>-server -Xms1024M -Xmx1024M -XX:PermSize=128m -XX:MaxPermSize=256m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:\\\${JBOSS_HOME}/server/SLOT_NAME/log/gc.log -Datg.dynamo.layers=ci -Djboss.platform.mbeanserver</jvm_opts>
			</slot>
			<slot name="slot2" type="CtrlPrimary" jbossDomain="CTRL1" logFileRetentionDays="20" jbossClusterMCastAddr="239.255.3.14">
				<jvm_opts>-server -Xms1024M -Xmx1024M -XX:PermSize=128m -XX:MaxPermSize=256m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:\\\${JBOSS_HOME}/server/SLOT_NAME/log/gc.log -Datg.dynamo.layers=ci -Djboss.platform.mbeanserver</jvm_opts>
			</slot>
			<slot name="slot3" type="PS" jbossDomain="A1" logFileRetentionDays="5" jbossClusterMCastAddr="239.255.3.15">
				<jvm_opts>-server -Xms1024M -Xmx1024M -XX:PermSize=128m -XX:MaxPermSize=256m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:\\\${JBOSS_HOME}/server/SLOT_NAME/log/gc.log -Datg.dynamo.layers=ci -Djboss.platform.mbeanserver</jvm_opts>
			</slot>
			<slot name="slot4" type="PS" jbossDomain="A1" logFileRetentionDays="5" jbossClusterMCastAddr="239.255.3.15">
